//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string ButtonArea {
            get {
                return ResourceManager.GetString("ButtonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black background.
        /// </summary>
        internal static string ButtonBackGround {
            get {
                return ResourceManager.GetString("ButtonBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string ButtonDistance {
            get {
                return ResourceManager.GetString("ButtonDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to window.
        /// </summary>
        internal static string ButtonFitToWindow {
            get {
                return ResourceManager.GetString("ButtonFitToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CSV.
        /// </summary>
        internal static string ButtonGetCSV {
            get {
                return ResourceManager.GetString("ButtonGetCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ButtonInfo {
            get {
                return ResourceManager.GetString("ButtonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string ButtonLayers {
            get {
                return ResourceManager.GetString("ButtonLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from HDD.
        /// </summary>
        internal static string ButtonLoadFromHDD {
            get {
                return ResourceManager.GetString("ButtonLoadFromHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from Web.
        /// </summary>
        internal static string ButtonLoadFromWeb {
            get {
                return ResourceManager.GetString("ButtonLoadFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbit.
        /// </summary>
        internal static string ButtonOrbit {
            get {
                return ResourceManager.GetString("ButtonOrbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline.
        /// </summary>
        internal static string ButtonPolyline {
            get {
                return ResourceManager.GetString("ButtonPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string ButtonZoomIn {
            get {
                return ResourceManager.GetString("ButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string ButtonZoomOut {
            get {
                return ResourceManager.GetString("ButtonZoomOut", resourceCulture);
            }
        }
    }
}
